### ISSUE TITLE
create_android.sh not found in repo

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/app-backend-rust#101]
**Describe the bug**
Script for creating android library not pushed to reo

**Additional context**
Script is referenced in [Building-library-for-Android](https://github.com/Co-Epi/app-backend-rust/wiki/Building-library-for-Android)

```
sh ./scripts/android/create_android.sh
```

**Comment by ivnsch** [comment]
The script is now here: https://github.com/Co-Epi/app-backend-rust/tree/master/android/scripts

**Comment by duskoo** [comment]
Ah... I expected it to be in scripts/android, not android/scripts.
iOS script is in scripts/ios.
