### ISSUE TITLE
Replace Persy with Sqlite?

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#106]
Similarly to the preferences, we're having weird Android issues with the Persy DB: https://github.com/Co-Epi/app-android/issues/280

Similarly to the preferences, it's an opportunity to reconsider why we're using Persy. This was part of the very early code we took over. The main reason to use it was probably the [indexing of the TCNs by timestamp](https://github.com/Co-Epi/app-backend-rust/commit/89fd43db13a2507bb6354563198bbae9dac42235#diff-b4aea3e418ccdb71239b96952d9cddb6R19), used to [filter them by time interval](https://github.com/Co-Epi/app-backend-rust/commit/89fd43db13a2507bb6354563198bbae9dac42235#diff-b4aea3e418ccdb71239b96952d9cddb6R38). If this requirement is not up to date, there's doesn't seem to be a reason to use Persy.

We support now Sqlite, which is more mature and easy to work with. Having to maintain multiple databases is also a burden in general, and slows down bootstrap (which we currently have to execute in the main thread), so unless there's a good reason not to, we should use it.

Tasks:
- Confirm whether we will not need at some point to index TCNs by timestamp.
- If we will need it, confirm that Persy's index is more performant than Sqlite's. It's likely that the original author preferred Persy only because it's lightweight. Given that we have now Sqlite anyway, this would not be of relevance.
- If we need it and the performance is better, confirm that the difference is relevant to us: Most of the time is spent with the in-memory matching, so a few milliseconds more fetching the records is unlikely to make a difference. Inserting TCNs is also not (very) performance demanding.
- If we don't need it, migrate the TCNs to sqlite.

**Comment by duskoo** [comment]
https://github.com/Co-Epi/app-android/issues/280 is specific to Huawei flavor of Android.
Number of dependencies should be minimized - agreed.
persy is Rust native db, while [SQLite is C library](https://www.sqlite.org/index.html) with [rusqlite acting as a wrapper](https://docs.rs/rusqlite/0.23.1/rusqlite/). On the other hand, seems that persy has [only one person as developer/maintainer](https://gitlab.com/tglman/persy/-/project_members), which is problematic.

...

Interesting article on rusqlite performance: [Investigating Rust with SQLite](https://tedspence.com/investigating-rust-with-sqlite-53d1f9a41112)
[Some other embeddable DBs for Rust](https://users.rust-lang.org/t/embeddable-db-in-rust/22100/4)

**Comment by ivnsch** [comment]
Thanks for the links. The tldr from the "Investigating Rust with SQLite" article seems to be to batch writes. Ideally we'd not have to do this with the TCNs. We're anyway talking only of max. a few hundreds at a time and not tens of thousands, like in typical backend applications. But it would be good anyway if you compare the performance with Persy. Maybe it's relevant for battery consumption. Prepared statements seems a minor optimization, probably not worth for us.

LMDB is definitely interesting for the TCNs and preferences, but at the moment I'd aim more at simplicity and correctness. Having to maintain 2 databases (in particular without having benchmarked or even fully tested anything), seems like premature optimization.

Note that part of the reason I added Sqlite support is because (aside of the alerts), we plan to add more structured data in the future (journal feature), for which key value stores are not optimal.

**Comment by ivnsch** [comment]
Though I'm not against giving LMDB a try. Can you write some benchmark tests with Persy / Sqlite / LMDB (without integrating them in the app, just write / read TCNs and anything else that may be relevant)?

**Comment by duskoo** [comment]
- I don't see the need to index TCNs by timestamp. If the need arises, we can add such index to whichever DB we pick.
- Persy beng rust native was likely a factor to use it (initially). As it is not pointed out otherwise, we can assume that both persy and sqlite use Btree based indexes (default data structure in "classic" DBs): this means similar performance, but worth confirming nevertheless. 
- Only DB ops we currently use are "save single TCN" and "load all TCNs" - I will use those for benchmarks.

**Comment by duskoo** [comment]
Preliminary results:
Operation|Persy | rusqlite
------------ | ------------ | -------------
save 100 records| 464.091311ms, 676.424309ms| 97.746231ms, 88.603022ms
save 100 records in single transaction| 30.853613ms, 19.206823ms |        x
load ~10k records|(9913 rec) bench: 186,553,579 ns/iter (+/- 134,647,326) | (13603 rec) bench: 126,548,067 ns/iter (+/- 16,008,466)

**Comment by ivnsch** [comment]
Well, this settles it 🙂 (for completeness: what does the x mean?)

It makes sense to keep the sqlite benchmarks in our code. Open a PR?

If you don't have time to continue, I can take over.
