### ISSUE TITLE
DB migrations (reset) mechanism

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#124]
We should support versioning the database (similarly to how it's done with Realm in the apps), to at least reset it when the version is updated.

Current context: The TCNs table is getting new columns in 0.4, which will make the app crash for users updating from 0.3. 

We can alternatively tell the testers to delete and reinstall the app, but this is not ideal.

**Comment by duskoo** [comment]
Apparently, SQLite migrations are built around 
```
PRAGMA user_version;
```
statement, with custom logic attached.
[SO: Best Practices for in-app Database Migration](https://stackoverflow.com/questions/989558/best-practices-for-in-app-database-migration-for-sqlite)

**Comment by ivnsch** [comment]
@duskoo iOS 0.4 should be done today, what's the status of this? I assume that most testers will be new (don't have an old version installed), but it would still be nice to have this.

**Comment by duskoo** [comment]
Hi @i-schuetz , plan is to finish the feature today.

**Comment by duskoo** [comment]
Implemented
