### ISSUE TITLE
Change alert unique

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#133]
Currently the alert's primary key is the report signature.
This is not in sync with the current spec, where there can be multiple exposures (and thus alerts) for one report.

The unique should:
- Allow to delete alerts
- Prevent restoring alerts when re-fetching in a given time interval

**Comment by duskoo** [comment]
Proposal:
```
report_signature || exposure_ratchet_index
```
Concatenating ratchet index corresponding to interval during which the exposure took place to the signature looks like a good solution to me.

**Comment by i-schuetz** [comment]
An exposure can contain multiple TCNs / intervals. I guess that we can concatenate the indices.

**Comment by ivnsch** [comment]
The relationship between exposures and TCNs is n:n. A single exposure may consist of multiple TCNs, and a TCN may contain multiple exposures (to be expected only on iOS, where we don't update the TCN each 15 mins).

This means that unless we change the n:n relationship, we should use something else. I'd suggest `report_signature || exposure_start_time`.
