### ISSUE TITLE
Submit report integration and unit tests

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#14]
Integration tests:
- Improve testability of `SymptomInputsSubmitter.submit_inputs`
- Test: mapping of symptom inputs -> public report -> signed report (TCN library) -> final report string (as sent to api) and back to signed report (TCN library) -> public report (note: Test should not include the api call).
- Add Unit Tests for smaller parts if needed.

Implement either separately (see `is_it_working.rs`) or file-level (see existing tests in `mappers.rs` or `memo.rs`) in `symptom_inputs.rs`.

Possible bug fixing can be submitted in a separate PR.

**Comment by duskoo** [comment]
Fixed by #30
