### ISSUE TITLE
Forward logs to apps

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#28]
After https://github.com/Co-Epi/app-backend-rust/issues/27 is implemented, allow the apps to register a callback in order to forward the logs (e.g. to be displayed in a debug screen).

Notes:
- Use struct pointers. Forwarding logs as JSON seems to inefficient, even for debug mode.
- Consider keeping the logging directly in Rust and in the apps not using these logs for console logging. This is to keep logs in the case that something goes wrong with the forwarding.

**Comment by ivnsch** [comment]
@duskoo actually, since the logger is a global variable, we should be able to expose a global FFI function to Rust?

**Comment by duskoo** [comment]
@i-schuetz You mean something like this: [Accessing foreign globals](https://doc.rust-lang.org/nomicon/ffi.html#accessing-foreign-globals) ?
And for the second point:

> Consider keeping the logging directly in Rust and in the apps not using these logs for console logging. This is to keep logs in the case that something goes wrong with the forwarding.

Not sure what you mean here. Is the idea to save the logs to  files? Rust would have its own file, separate from the app log file.

**Comment by ivnsch** [comment]
It just crossed my mind to use FFI "in the other direction", but it's probably complicated / impossible, so let's stick to the callback.

The second point also can be ignored. It's about keeping a `println!` in Rust for the console logging (while not re-printing in Swift), in case something goes wrong with the callback, but this seems unnecessary. If the callback works reliably in our tests it's unlikely that it will fail in the future.

**Comment by duskoo** [comment]
Ok. The current plan is to use [log crate](https://docs.rs/log/0.4.8/log/) as a facade which will provide us with macros: error!, warn!, info!, debug! and trace! which we will sprinkle through Rust code.
I will add a custom logger that will implement the log fn (declared in log crate): this will pass the data to the callback and can also do println.
