### ISSUE TITLE
Investigate if it's possible to use enums with associated values in FFI (iOS)

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#39]
This would allow to return `Result`.

**Comment by duskoo** [comment]
Quote from a 5 year old article:
> We’re writing a library in Rust, but need to expose its public interface in a
C header, so we’re restricted to data types that are compatible with C. This
means, for example, no generics or enums that hold
data. Swift supports both of those itself, but not in a way
that’s compatible with Rust.

Source: [BNR Designing an API for our Rust layer](https://www.bignerdranch.com/blog/building-an-ios-app-in-rust-part-2-passing-primitive-data-between-rust-and-ios/)

Looks like passing enums with assoc. values is not feasible.

**Comment by ivnsch** [comment]
Ok, it's likely that this hasn't changed, as C doesn't support it.
