### ISSUE TITLE
Replace / update confy

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#84]
Not working on Android: https://github.com/rust-cli/confy/issues/31

Unless they add support soon, we need something else to manage preferences.

**Comment by duskoo** [comment]
Is there anything else in the logs?
Did you try with real application name: confy::load("coepi")?
Which Android version you tested with?
App has write permissions fro storage?

Confy uses crate directories underneath. It has special handling for Linux/MacOS/Win. Other systems (iOS, Android) are handled as Linux (according to docs).
https://github.com/rust-cli/confy/blob/baf2b401c9b4e783599ac8c74a6a9829a27f0deb/src/lib.rs#L118
https://github.com/dirs-dev/directories-rs/blob/main/src/lib.rs#L392
https://github.com/dirs-dev/directories-rs/blob/a09f8717ac47f5d153946f1e1b351aa9de293c57/src/lin.rs#L86

**Comment by ivnsch** [comment]
The used [Linux directory](https://github.com/dirs-dev/directories-rs/blob/main/src/lib.rs#L414) (`/home/...`) [doesn't exist / is not accessible](https://android.stackexchange.com/questions/64046/where-is-the-home-folder) on Android. I'm writing a replacement using sqlite, which we will need for the alerts storage anyway. Performance will likely be fine (for the current flows it's not a problem anyway, as they're executed in the background). If it's not, we can look for another storage. Confy's performance for this kind of storage was also never clear.

**Comment by ivnsch** [comment]
> Other systems (iOS, Android) are handled as Linux (according to docs)

I couldn't find anything explicit about Android btw. Where is this?

**Comment by Dylan-DPC-zz** [comment]
One of confy maintainers here. Android permissions is always a tough ask and a tough thing to maintain. Given our (the crate belongs to the CLI working group) bandwidths, we may not be able to fix it but if any of you know a fix, feel free to PR it and we can issue a new release after that :) Thanks

**Comment by duskoo** [comment]
@i-schuetz 
Android platform support:
[Directories crate: platforms](https://github.com/dirs-dev/directories-rs#platforms)

> This library is written in Rust, and supports Linux, Redox, macOS and Windows. Other platforms are also supported; they use the Linux conventions.

Specifically here: 
https://github.com/dirs-dev/directories-rs/blob/main/src/lib.rs#L27
MacOs and iOs are using **mod mac**, while Android is handled by default **mod lin** (Linux)

**Comment by ivnsch** [comment]
@duskoo thus "explicit" 😉 (though being included under "other" can be arguably considered explicit).

I'll not be doing a PR, so unless you want to do it, I think that it's reasonable to try out sqlite for now (given that we need it anyway).

**Comment by ivnsch** [comment]
@Dylan-DPC we're unlikely to collaborate with the feature (not very experienced with Rust yet), but in any case would recommend adding a note about this to the docs. As per @duskoo's comment above, the docs imply that all platforms are supported, which is misleading. It would have saved us some time.

**Comment by Dylan-DPC-zz** [comment]
> not very experienced with Rust yet

That's fine we are ready to mentor you

**Comment by ivnsch** [comment]
That was a (poorly chosen) shorthand for "not experienced with Rust and Android's file system permissions and genuinely don't have time anyway", but thanks 😄
