### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#90]
Configure a workflow in Github Actions:

<img width="676" alt="Screen Shot 2020-06-23 at 17 33 12" src="https://user-images.githubusercontent.com/1381744/85423982-a90a9480-b577-11ea-8200-e577c6774608.png">

See e.g. [TCN repo](https://github.com/TCNCoalition/TCN/actions?query=workflow%3A%22Continuous+integration%22)

**Comment by ivnsch** [comment]
@mellowgeek Any update?

**Comment by i-schuetz** [comment]
Ok this was 2 secs so I added it.

**Comment by ivnsch** [comment]
Solved. Note that the "Rust build" step also runs the tests.

<img width="981" alt="Screen Shot 2020-06-30 at 09 56 05" src="https://user-images.githubusercontent.com/1381744/86099572-f75bee00-bab7-11ea-8f29-ce70521d8439.png">
