### ISSUE TITLE
Android binaries size

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-backend-rust#96]
The Android core binaries (created with --release) are 20-30 MB per target. The APK size went up from ~12 MB to ~39 MB. What is causing this? How to reduce the size? On iOS integrating core increased the final app size by only ~1 MB.

Note: We had to turn off AAB (see https://github.com/Co-Epi/app-android/issues/272), which affects app size, but it shouldn't be significant.

**Comment by ivnsch** [comment]
Probably relevant:
https://stackoverflow.com/a/50637280/930450
https://github.com/johnthagen/min-sized-rust
https://github.com/RazrFalcon/cargo-bloat

**Comment by mellowgeek** [comment]
APK size is large because it includes the .so files for all targets right now.

**Comment by ivnsch** [comment]
For the record, as discussed, this would have to be fixed to create one APK per architecture (see e.g. https://developer.android.com/google/play/publishing/multiple-apks), but we will focus on fixing the AAB build (https://github.com/Co-Epi/app-android/issues/272)

**Comment by ivnsch** [comment]
I upgraded core to in the app to 0.1.19 and created build [88](https://appcenter.ms/users/scottleibrand/apps/CoEpi-Android/build/branches/develop/builds/88) with AAB enabled. AppCenter still offers an APK with all the architectures / 33 MB. 

Please investigate and document:

1. Is this an AppCenter only thing? If yes, is there an easy way around? (low prio)
2. Does the Play Store strip the not used architectures from the AAB? (high prio as this concerns the end users). We'd have to setup the Play Store account to test that and use the internal/alpha release channels. @scottleibrand

**Comment by i-schuetz** [comment]
I'd expect this to be an AppCenter only issue:


> Google Play uses your app bundle to generate and serve optimized APKs for each device configuration, so only the code and resources that are needed for a specific device are downloaded to run your app. You no longer have to build, sign, and manage multiple APKs to optimize support for different devices, and users get smaller, more-optimized downloads.

**Comment by ivnsch** [comment]
I'd expect this to be an AppCenter only issue:

> Google Play uses your app bundle to generate and serve optimized APKs for each device configuration, so only the code and resources that are needed for a specific device are downloaded to run your app. You no longer have to build, sign, and manage multiple APKs to optimize support for different devices, and users get smaller, more-optimized downloads.

But let's confirm everything. We've to setup the Play Store account anyway and now it would be a great point to do that.

It would be also good to see if we can easily do something to reduce the download size for AppCenter testers. A small improvement for the later, if nothing else is possible, would be to adjust Gradle to not include the emulator binaries when the app is being built in AppCenter. It this is needed we can create a separate (low prio) issue for it.

**Comment by mellowgeek** [comment]
Per [https://docs.microsoft.com/en-us/appcenter/distribution/uploading](https://docs.microsoft.com/en-us/appcenter/distribution/uploading):

> You can only distribute Android app bundles to the Google Play Store, not to groups or individual testers.

**Comment by ivnsch** [comment]
Closing this as it seems mostly cleared and it's unclear when we'll have a Play Store account. If we notice issues with the AAB we'll reopen it.
